# Generated by Django 3.0.6 on 2020-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200531_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tag1',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag3',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
