# Generated by Django 2.2.9 on 2020-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200418_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, default='No information about the author.', max_length=5000, null=True),
        ),
    ]
