# Generated by Django 3.0.5 on 2020-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200421_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
