# Generated by Django 3.0.5 on 2020-04-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200425_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Post',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
    ]
