# Generated by Django 2.2.9 on 2020-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Animals', 'Animals'), ('Birds', 'Birds'), ('Business', 'Business'), ('Health', 'Health'), ('Movies', 'Movies'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=2, null=True),
        ),
    ]
