# Generated by Django 2.2.9 on 2020-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200524_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Animals', 'Animals'), ('Birds', 'Birds'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Food', 'Food'), ('Health', 'Health'), ('Movies', 'Movies'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Others', 'Others')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
