# Generated by Django 2.2.9 on 2020-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200524_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Animals', 'Animals'), ('Birds', 'Birds'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Food', 'Food'), ('Health', 'Health'), ('Movies', 'Movies'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Others', 'Others')], default='Others', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Hello', max_length=10000),
            preserve_default=False,
        ),
    ]
